apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-dev1
spec:
  interval: 1m
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-dev1
  targetNamespace: flux-dev1
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
