apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: flux-dev1
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:MdSt2W/Z894t2Giuj1Ghsv2FDi2nYrnBuC6BH/abbvIneA19MFUGb9O3140=,iv:8dzyCBEhyrPZv+9l4w8KE12nlavTUdgXrf6fDz8J2F4=,tag:VXSFxmrhmQZu/ORPyGF8/w==,type:str]
sops:
    age:
        - recipient: age1h77h5ex36y9deh9eucvyegdypcfgkurdy35vvz86et082xfyjyrsu9zlzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVdWVXlMcHl0TlFMSUVU
            TjNZYjQ1dWdnbjJOdGpORUFFNEZuQXg0Y1VZCkNkYmxNckRVeFNseG9laXo0K011
            SkU5cUNsakhQcERQNGpZbXVZeWo2YmcKLS0tIEJvYmhZOGQ3cTJDUkoxbHNUaUkz
            a0lCS3pqenF0WHJNY2ZvN3FBY3h0Nk0Kv3vgXlyvCYK3zl7J1hhQJW7+wQCVsFld
            w4PWA1xkzq69BpFvJ/264ro7yReywBr1rkt4ZnjrB2bGi0c4wCMkGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T15:34:04Z"
    mac: ENC[AES256_GCM,data:jgCHrGLqFqBowgSx+mvNOOAH9q4sfbCPNSeuO82BIXhHS3WEFddPeMI54nwJLzZvhipcI+39G4YL/n0u2pKKF2q/GyTIjIpB5maDdTdnK6e7bgcqDcgnoQOVTDZVoCVPcBwQjUCihO9gl/Et6rMfY6N3iB/z7P77+WgjMRgf9+o=,iv:QR5CQVoTL117BKCPFMYyK0nSuhBORvdPWm5zY9WdCuM=,tag:6hvKgdOc7ZhQOfx6HIVHXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
